version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    # Lightweight Redis container for caching feature flags

  featureflagservice:
    build: .
    container_name: featureflagservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis
    # Spring Boot app that uses Redis as backend storage