version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  featureflagservice:
    image: ghcr.io/your-org/featureflagservice:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_ACTUATOR_METRICS_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
